#ifndef IR_H
#define IR_H

#include <stdint.h>

#include "assembly.h"
#include "memTrace.h"
#include "variableRange.h"
#include "graph.h"
#include "graphPrintDot.h"
#include "array.h"

#define IRLAYER

enum irOpcode{
	IR_ADC 		= 0,
	IR_ADD 		= 1,
	IR_AND 		= 2,
	IR_CMOV 	= 3, 	/* temp */
	IR_DIVQ 	= 4,
	IR_DIVR 	= 5,
	IR_IDIV 	= 6,
	IR_IMUL 	= 7,
	IR_LEA 		= 8, 	/* importer */
	IR_MOV 		= 9, 	/* importer */
	IR_MOVZX 	= 10,
	IR_MUL 		= 11,
	IR_NEG 		= 12,
	IR_NOT 		= 13,
	IR_OR 		= 14,
	IR_PART1_8 	= 15, 	/* specific */
	IR_PART2_8 	= 16, 	/* specific */
	IR_PART1_16 = 17, 	/* specific */
	IR_ROL 		= 18,
	IR_ROR 		= 19,
	IR_SHL 		= 20,
	IR_SHLD 	= 21,
	IR_SHR 		= 22,
	IR_SHRD 	= 23,
	IR_SUB 		= 24,
	IR_XOR 		= 25,
	IR_LOAD 	= 26, 	/* signature */
	IR_STORE 	= 27, 	/* signature */
	IR_JOKER 	= 28, 	/* signature */
	IR_INVALID 	= 29 	/* specific */
};

#define NB_IR_OPCODE 30 /* after updating this value, please grep in the code because a lot of static arrays depend on this value */

const char* irOpcode_2_string(enum irOpcode opcode);

enum irRegister{
	IR_REG_EAX 			= 0,
	IR_REG_AX 			= 1,
	IR_REG_AH 			= 2,
	IR_REG_AL 			= 3,
	IR_REG_EBX 			= 4,
	IR_REG_BX 			= 5,
	IR_REG_BH 			= 6,
	IR_REG_BL 			= 7,
	IR_REG_ECX 			= 8,
	IR_REG_CX 			= 9,
	IR_REG_CH 			= 10,
	IR_REG_CL 			= 11,
	IR_REG_EDX 			= 12,
	IR_REG_DX 			= 13,
	IR_REG_DH 			= 14,
	IR_REG_DL 			= 15,

	IR_REG_ESP 			= 16,
	IR_REG_SP 			= 17,
	IR_REG_EBP 			= 18,
	IR_REG_BP 			= 19,
	IR_REG_ESI 			= 20,
	IR_REG_SI 			= 21,
	IR_REG_EDI 			= 22,
	IR_REG_DI 			= 23,

	IR_REG_TMP 			= 24, 	/* importer */

	/* Bit map description for the SIMD register
		- [0 :7 ] 	frag
		- [8 :11] 	size {1:8, 2:16, 4:32}
		- [12:15] 	index
		- [16:18] 	type {1:MMX, 2:XMM, 3:YMM, 4:Virtual (see below)}
		- [19:31] 	--
	*/

	#define IR_REGISTER_SIMD_SIZE_8 	0x00000100
	#define IR_REGISTER_SIMD_SIZE_16 	0x00000200
	#define IR_REGISTER_SIMD_SIZE_32 	0x00000400

	#define IR_REGISTER_SIMD_INDEX_1 	0x00000000
	#define IR_REGISTER_SIMD_INDEX_2 	0x00001000
	#define IR_REGISTER_SIMD_INDEX_3 	0x00002000
	#define IR_REGISTER_SIMD_INDEX_4 	0x00003000
	#define IR_REGISTER_SIMD_INDEX_5 	0x00004000
	#define IR_REGISTER_SIMD_INDEX_6 	0x00005000
	#define IR_REGISTER_SIMD_INDEX_7 	0x00006000
	#define IR_REGISTER_SIMD_INDEX_8 	0x00007000

	#define IR_REGISTER_SIMD_MMX 		0x00010000
	#define IR_REGISTER_SIMD_XMM 		0x00020000
	#define IR_REGISTER_SIMD_YMM 		0x00030000

	IR_REG_XMM1_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM1_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM1_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM1_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_XMM2_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM2_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM2_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM2_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_XMM3_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM3_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM3_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM3_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_XMM4_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM4_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM4_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM4_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_XMM5_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM5_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM5_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM5_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_XMM6_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM6_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM6_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM6_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_XMM7_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM7_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM7_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM7_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_XMM8_32_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_XMM8_32_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_XMM8_32_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_XMM8_32_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 3,

	IR_REG_XMM1_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM1_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM1_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM1_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM1_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM1_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM1_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM1_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_XMM2_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM2_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM2_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM2_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM2_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM2_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM2_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM2_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_XMM3_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM3_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM3_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM3_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM3_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM3_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM3_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM3_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_XMM4_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM4_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM4_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM4_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM4_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM4_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM4_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM4_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_XMM5_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM5_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM5_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM5_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM5_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM5_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM5_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM5_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_XMM6_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM6_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM6_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM6_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM6_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM6_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM6_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM6_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_XMM7_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM7_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM7_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM7_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM7_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM7_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM7_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM7_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_XMM8_16_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_XMM8_16_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_XMM8_16_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_XMM8_16_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_XMM8_16_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_XMM8_16_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_XMM8_16_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_XMM8_16_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 7,

	IR_REG_XMM1_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM1_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM1_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM1_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM1_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM1_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM1_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM1_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM1_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM1_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM1_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM1_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM1_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM1_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM1_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM1_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_XMM2_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM2_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM2_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM2_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM2_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM2_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM2_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM2_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM2_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM2_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM2_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM2_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM2_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM2_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM2_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM2_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_XMM3_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM3_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM3_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM3_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM3_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM3_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM3_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM3_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM3_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM3_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM3_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM3_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM3_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM3_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM3_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM3_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_XMM4_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM4_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM4_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM4_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM4_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM4_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM4_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM4_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM4_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM4_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM4_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM4_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM4_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM4_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM4_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM4_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_XMM5_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM5_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM5_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM5_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM5_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM5_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM5_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM5_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM5_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM5_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM5_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM5_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM5_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM5_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM5_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM5_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_XMM6_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM6_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM6_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM6_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM6_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM6_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM6_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM6_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM6_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM6_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM6_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM6_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM6_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM6_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM6_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM6_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_XMM7_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM7_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM7_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM7_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM7_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM7_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM7_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM7_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM7_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM7_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM7_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM7_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM7_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM7_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM7_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM7_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_XMM8_8_1 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_XMM8_8_2 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_XMM8_8_3 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_XMM8_8_4 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_XMM8_8_5 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_XMM8_8_6 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_XMM8_8_7 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_XMM8_8_8 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_XMM8_8_9 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_XMM8_8_10 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_XMM8_8_11 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_XMM8_8_12 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_XMM8_8_13 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_XMM8_8_14 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_XMM8_8_15 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_XMM8_8_16 	= IR_REGISTER_SIMD_XMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 15,

	IR_REG_MMX1_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX1_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_MMX2_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX2_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_MMX3_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX3_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_MMX4_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX4_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_MMX5_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX5_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_MMX6_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX6_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_MMX7_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX7_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_MMX8_32_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_MMX8_32_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 1,

	IR_REG_MMX1_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX1_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX1_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX1_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_MMX2_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX2_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX2_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX2_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_MMX3_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX3_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX3_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX3_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_MMX4_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX4_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX4_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX4_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_MMX5_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX5_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX5_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX5_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_MMX6_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX6_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX6_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX6_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_MMX7_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX7_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX7_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX7_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_MMX8_16_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_MMX8_16_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_MMX8_16_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_MMX8_16_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 3,

	IR_REG_MMX1_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX1_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX1_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX1_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX1_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX1_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX1_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX1_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_MMX2_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX2_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX2_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX2_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX2_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX2_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX2_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX2_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_MMX3_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX3_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX3_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX3_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX3_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX3_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX3_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX3_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_MMX4_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX4_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX4_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX4_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX4_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX4_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX4_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX4_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_MMX5_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX5_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX5_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX5_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX5_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX5_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX5_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX5_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_MMX6_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX6_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX6_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX6_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX6_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX6_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX6_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX6_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_MMX7_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX7_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX7_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX7_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX7_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX7_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX7_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX7_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_MMX8_8_1 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_MMX8_8_2 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_MMX8_8_3 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_MMX8_8_4 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_MMX8_8_5 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_MMX8_8_6 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_MMX8_8_7 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_MMX8_8_8 	= IR_REGISTER_SIMD_MMX | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 7,

	IR_REG_YMM1_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM1_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM1_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM1_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_YMM2_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM2_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM2_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM2_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_YMM3_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM3_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM3_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM3_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_YMM4_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM4_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM4_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM4_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_YMM5_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM5_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM5_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM5_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_YMM6_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM6_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM6_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM6_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_YMM7_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM7_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM7_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM7_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_32 | 3,
	IR_REG_YMM8_32_5 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 0,
	IR_REG_YMM8_32_6 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 1,
	IR_REG_YMM8_32_7 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 2,
	IR_REG_YMM8_32_8 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_32 | 3,

	IR_REG_YMM1_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM1_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM1_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM1_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM1_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM1_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM1_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM1_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_YMM2_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM2_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM2_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM2_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM2_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM2_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM2_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM2_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_YMM3_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM3_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM3_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM3_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM3_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM3_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM3_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM3_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_YMM4_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM4_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM4_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM4_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM4_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM4_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM4_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM4_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_YMM5_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM5_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM5_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM5_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM5_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM5_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM5_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM5_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_YMM6_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM6_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM6_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM6_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM6_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM6_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM6_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM6_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_YMM7_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM7_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM7_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM7_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM7_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM7_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM7_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM7_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_16 | 7,
	IR_REG_YMM8_16_9 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 0,
	IR_REG_YMM8_16_10 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 1,
	IR_REG_YMM8_16_11 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 2,
	IR_REG_YMM8_16_12 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 3,
	IR_REG_YMM8_16_13 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 4,
	IR_REG_YMM8_16_14 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 5,
	IR_REG_YMM8_16_15 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 6,
	IR_REG_YMM8_16_16 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_16 | 7,

	IR_REG_YMM1_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM1_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM1_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM1_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM1_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM1_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM1_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM1_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM1_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM1_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM1_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM1_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM1_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM1_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM1_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM1_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_1 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_YMM2_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM2_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM2_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM2_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM2_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM2_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM2_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM2_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM2_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM2_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM2_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM2_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM2_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM2_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM2_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM2_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_2 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_YMM3_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM3_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM3_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM3_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM3_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM3_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM3_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM3_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM3_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM3_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM3_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM3_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM3_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM3_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM3_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM3_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_3 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_YMM4_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM4_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM4_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM4_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM4_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM4_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM4_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM4_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM4_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM4_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM4_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM4_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM4_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM4_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM4_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM4_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_4 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_YMM5_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM5_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM5_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM5_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM5_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM5_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM5_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM5_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM5_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM5_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM5_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM5_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM5_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM5_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM5_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM5_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_5 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_YMM6_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM6_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM6_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM6_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM6_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM6_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM6_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM6_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM6_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM6_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM6_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM6_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM6_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM6_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM6_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM6_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_6 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_YMM7_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM7_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM7_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM7_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM7_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM7_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM7_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM7_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM7_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM7_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM7_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM7_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM7_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM7_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM7_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM7_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_7 | IR_REGISTER_SIMD_SIZE_8 | 15,
	IR_REG_YMM8_8_17 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 0,
	IR_REG_YMM8_8_18 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 1,
	IR_REG_YMM8_8_19 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 2,
	IR_REG_YMM8_8_20 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 3,
	IR_REG_YMM8_8_21 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 4,
	IR_REG_YMM8_8_22 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 5,
	IR_REG_YMM8_8_23 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 6,
	IR_REG_YMM8_8_24 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 7,
	IR_REG_YMM8_8_25 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 8,
	IR_REG_YMM8_8_26 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 9,
	IR_REG_YMM8_8_27 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 10,
	IR_REG_YMM8_8_28 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 11,
	IR_REG_YMM8_8_29 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 12,
	IR_REG_YMM8_8_30 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 13,
	IR_REG_YMM8_8_31 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 14,
	IR_REG_YMM8_8_32 	= IR_REGISTER_SIMD_YMM | IR_REGISTER_SIMD_INDEX_8 | IR_REGISTER_SIMD_SIZE_8 | 15,
};

#define NB_IR_STD_REGISTER 25
#define NB_IR_MMX_REGISTER 8
#define NB_IR_XMM_REGISTER 8
#define NB_IR_YMM_REGISTER 8

#define irRegister_is_std(reg) ((reg) < NB_IR_STD_REGISTER)
#define irRegister_is_mmx(reg) (((reg) & 0x00070000)== IR_REGISTER_SIMD_MMX)
#define irRegister_is_xmm(reg) (((reg) & 0x00070000)== IR_REGISTER_SIMD_XMM)
#define irRegister_is_ymm(reg) (((reg) & 0x00070000)== IR_REGISTER_SIMD_YMM)

#define irRegister_simd_get_index(reg) (((reg) >> 12) & 0x0000000f)
#define irRegister_simd_get_size(reg)  ((((reg) >> 8) & 0x0000000f) << 3)
#define irRegister_simd_get_frag(reg)  ((reg) & 0x000000ff)

#define irRegister_simd_frag(reg, size, frag) (((reg) & 0xfffff000) | ((((size) >> 3) & 0x00000007) << 8) | (((frag) + (irRegister_simd_get_frag(reg) * irRegister_simd_get_size(reg)) / (size)) & 0x0000000f))

const char* irRegister_2_string(enum irRegister reg);

#define IR_VIR_REGISTER_OFFSET 0x00040000

enum irVirtualRegister{
	IR_VREG_MMX1 = IR_VIR_REGISTER_OFFSET + 0,
	IR_VREG_MMX2 = IR_VIR_REGISTER_OFFSET + 1,
	IR_VREG_MMX3 = IR_VIR_REGISTER_OFFSET + 2,
	IR_VREG_MMX4 = IR_VIR_REGISTER_OFFSET + 3,
	IR_VREG_MMX5 = IR_VIR_REGISTER_OFFSET + 4,
	IR_VREG_MMX6 = IR_VIR_REGISTER_OFFSET + 5,
	IR_VREG_MMX7 = IR_VIR_REGISTER_OFFSET + 6,
	IR_VREG_MMX8 = IR_VIR_REGISTER_OFFSET + 7,
	IR_VREG_XMM1 = IR_VIR_REGISTER_OFFSET + 8,
	IR_VREG_XMM2 = IR_VIR_REGISTER_OFFSET + 9,
	IR_VREG_XMM3 = IR_VIR_REGISTER_OFFSET + 10,
	IR_VREG_XMM4 = IR_VIR_REGISTER_OFFSET + 11,
	IR_VREG_XMM5 = IR_VIR_REGISTER_OFFSET + 12,
	IR_VREG_XMM6 = IR_VIR_REGISTER_OFFSET + 13,
	IR_VREG_XMM7 = IR_VIR_REGISTER_OFFSET + 14,
	IR_VREG_XMM8 = IR_VIR_REGISTER_OFFSET + 15,
	IR_VREG_YMM1 = IR_VIR_REGISTER_OFFSET + 16,
	IR_VREG_YMM2 = IR_VIR_REGISTER_OFFSET + 17,
	IR_VREG_YMM3 = IR_VIR_REGISTER_OFFSET + 18,
	IR_VREG_YMM4 = IR_VIR_REGISTER_OFFSET + 19,
	IR_VREG_YMM5 = IR_VIR_REGISTER_OFFSET + 20,
	IR_VREG_YMM6 = IR_VIR_REGISTER_OFFSET + 21,
	IR_VREG_YMM7 = IR_VIR_REGISTER_OFFSET + 22,
	IR_VREG_YMM8 = IR_VIR_REGISTER_OFFSET + 23,
};

#define NB_IR_VIR_REGISTER 24

#define irRegister_is_virtual(reg) (reg >= IR_VIR_REGISTER_OFFSET)

extern const uint32_t irRegister_simd_virt_base[4];

#define irRegister_simd_get_virtual(reg) (IR_VIR_REGISTER_OFFSET + irRegister_simd_virt_base[(((reg) >> 16) & 0x00000003)] + irRegister_simd_get_index(reg))

static inline enum irRegister irRegister_virtual_get_simd(enum irVirtualRegister vreg, uint32_t size, uint32_t frag){
	if (vreg - IR_VIR_REGISTER_OFFSET < 8){
		return IR_REGISTER_SIMD_MMX | ((vreg - IR_VIR_REGISTER_OFFSET) << 12) | (((size >> 3) & 0x00000007) << 8) | (frag & 0x00000007);
	}
	else if (vreg - IR_VIR_REGISTER_OFFSET < 16){
		return IR_REGISTER_SIMD_XMM | ((vreg - (IR_VIR_REGISTER_OFFSET + 8)) << 12) | (((size >> 3) & 0x00000007) << 8) | (frag & 0x0000000f);
	}
	else if (frag < 128 / size){
		return IR_REGISTER_SIMD_XMM | ((vreg - (IR_VIR_REGISTER_OFFSET + 16)) << 12) | (((size >> 3) & 0x00000007) << 8) | (frag & 0x000000f);
	}
	else{
		return IR_REGISTER_SIMD_YMM | ((vreg - (IR_VIR_REGISTER_OFFSET + 16)) << 12) | (((size >> 3) & 0x00000007) << 8) | ((frag - (128 / size)) & 0x000000f);
	}
}

enum irOperationType{
	IR_OPERATION_TYPE_IN_REG,
	IR_OPERATION_TYPE_IN_MEM,
	IR_OPERATION_TYPE_OUT_MEM,
	IR_OPERATION_TYPE_IMM,
	IR_OPERATION_TYPE_INST,
	IR_OPERATION_TYPE_SYMBOL
};

#define IR_OPERATION_STATUS_FLAG_NONE 		0x00000000
#define IR_OPERATION_STATUS_FLAG_FINAL 		0x00000001
#define IR_OPERATION_STATUS_FLAG_ERROR 		0x80000000
#define IR_OPERATION_STATUS_FLAG_TEST 		0x40000000
#define IR_OPERATION_STATUS_FLAG_TESTING 	0x20000000

#define IR_OPERATION_INDEX_ADDRESS 			0xfffffffd
#define IR_OPERATION_INDEX_IMMEDIATE 		0xfffffffe
#define IR_OPERATION_INDEX_UNKOWN 			0xffffffff

#define IR_OPERATION_DST_UNKOWN 			0xffffffff

#define IR_IN_REG_IS_PRIMER 				0x00000001

struct irOperation{
	enum irOperationType 			type;
	union {
		struct {
			enum irRegister 		reg;
			uint32_t 				primer;
		} 							in_reg;
		struct {
			struct node* 			prev;
			struct node* 			next;
			uint32_t 				order;
			ADDRESS 				con_addr;
		} 							mem;
		struct {
			uint64_t 				value;
		} 							imm;
		struct {
			enum irOpcode 			opcode;
			uint32_t 				dst;
			struct variableRange	range;
			uint32_t 				seed;
		} 							inst;
		struct {
			void* 					code_signature;
			void* 					result;
			uint32_t 				index;
		} 							symbol;
	} 								operation_type;
	uint8_t 						size;
	uint32_t 						index;
	uint32_t 						status_flag;
};

#define ir_node_get_operation(node) 	((struct irOperation*)node_get_data(node))
#define irOperation_get_node(operation) (((struct node*)(operation)) - 1)

#define ir_imm_operation_get_signed_value(op) 		((int64_t)(((op)->operation_type.imm.value & (0xffffffffffffffffULL >> (64 - (op)->size))) | ((((op)->operation_type.imm.value >> ((op)->size - 1)) & 0x0000000000000001ULL) ? (0xffffffffffffffffULL << (op)->size) : 0)))
#define ir_imm_operation_get_unsigned_value(op) 	((op)->operation_type.imm.value & (0xffffffffffffffffULL >> (64 - (op)->size)))

#define ir_mem_get_next(op) ((op).operation_type.mem.next);
#define ir_mem_get_prev(op) ((op).operation_type.mem.prev);

static inline void ir_mem_remove(struct irOperation* operation){
	if (operation->operation_type.mem.next != NULL){
		ir_node_get_operation(operation->operation_type.mem.next)->operation_type.mem.prev = operation->operation_type.mem.prev;
	}
	if (operation->operation_type.mem.prev != NULL){
		ir_node_get_operation(operation->operation_type.mem.prev)->operation_type.mem.next = operation->operation_type.mem.next;
	}
}

enum irDependenceType{
	IR_DEPENDENCE_TYPE_DIRECT 		= 0x00000000, 	/* 1  Default dependence type 											*/
	IR_DEPENDENCE_TYPE_ADDRESS 		= 0x00000001, 	/* 2  Address 															*/
	IR_DEPENDENCE_TYPE_SHIFT_DISP 	= 0x00000002, 	/* 3  Used for the last operand of {ROL, ROR, SHL, SHLD, SHR, SHLD} 	*/
	IR_DEPENDENCE_TYPE_DIVISOR 		= 0x00000003, 	/* 4  Used for the last operand of {DIV, IDIV} 							*/
	IR_DEPENDENCE_TYPE_ROUND_OFF 	= 0x00000004, 	/* 5  Used for the second operand of {SHLD, SHRD} 						*/
	IR_DEPENDENCE_TYPE_SUBSTITUTE 	= 0x00000005, 	/* 6  Used for the last operand of {SUB} 								*/
	IR_DEPENDENCE_TYPE_MACRO 		= 0x00000006 	/* 7  Signature input and output parameters 							*/
};

#define NB_DEPENDENCE_TYPE 7

struct irDependence{
	enum irDependenceType 		type;
	union{
		uint32_t 				macro;
	} 							dependence_type;
};

#define ir_edge_get_dependence(edge) 		((struct irDependence*)edge_get_data(edge))
#define irDependence_get_edge(dependence) 	(((struct edge*)(dependence)) - 1)

/* Bit map description of the macro parameter (read the edge labeling prior to modify this mapping)
	- [0 :6 ] 	reserved
	- [7] 		0 for input and 1 for output
	- [8 :15] 	fragment index 0 to 255
	- [16:23] 	argument index 0 to 255
	- [24:31] 	reserved
*/

#define IR_DEPENDENCE_MACRO_DESC_SET_INPUT(nf, na) 		((((nf) & 0x000000ff) << 8) | (((na) & 0x000000ff) << 16))
#define IR_DEPENDENCE_MACRO_DESC_SET_OUTPUT(nf, na) 	((((nf) & 0x000000ff) << 8) | (((na) & 0x000000ff) << 16) | 0x00000080)
#define IR_DEPENDENCE_MACRO_DESC_IS_INPUT(desc) 		(((desc) & 0x00000080) == 0x00000000)
#define IR_DEPENDENCE_MACRO_DESC_IS_OUTPUT(desc) 		(((desc) & 0x00000080) == 0x00000080)
#define IR_DEPENDENCE_MACRO_DESC_GET_FRAG(desc) 		(((desc) >> 8) & 0x000000ff)
#define IR_DEPENDENCE_MACRO_DESC_GET_ARG(desc) 			(((desc) >> 16) & 0x00000ff)

struct alias{
	struct node* 		ir_node;
	uint32_t 			order;
	uint8_t 			type;
};

#define IR_VIR_REGISTER_NB_FRAG_MAX 16

struct simdAlias{
	uint32_t 			frag_size;
	struct {
		struct node*	ir_node;
		uint8_t 		type;
	} 					fragAlias_buffer[IR_VIR_REGISTER_NB_FRAG_MAX];
};

#define IR_CALL_STACK_MAX_SIZE 	32
#define IR_CALL_STACK_PTR 		15 /* must be strictly smaller than IR_CALL_STACK_MAX_SIZE */

struct irBuilder{
	struct alias 		alias_buffer[NB_IR_STD_REGISTER];
	struct simdAlias 	simdAlias_buffer[NB_IR_VIR_REGISTER];

	uint32_t 			stack[IR_CALL_STACK_MAX_SIZE];
	uint32_t 			stack_ptr;
	uint32_t 			func_id;

	struct node* 		prev_mem_access;
	uint32_t 			reg_op_order;
};

struct ir{
	struct graph 		graph;
	uint32_t 			range_seed;
	struct irBuilder 	builder;
};

#define IR_INVALID_RANGE_SEED 0
#define ir_drop_range(ir) ((ir)->range_seed ++)

struct ir* ir_create(const struct assembly* assembly, const struct memTrace* mem_trace);
int32_t ir_init(struct ir* ir, const struct assembly* assembly, const struct memTrace* mem_trace);

struct irComponent{
	uint32_t 	instruction_start;
	uint32_t 	instruction_stop;
	struct ir*	ir;
};

struct ir* ir_create_compound(const struct assembly* assembly, const struct memTrace* mem_trace, struct irComponent** ir_component_buffer, uint32_t nb_ir_component);
int32_t ir_init_compound(struct ir* ir, const struct assembly* assembly, const struct memTrace* mem_trace, struct irComponent** ir_component_buffer, uint32_t nb_ir_component);

struct node* ir_add_in_reg(struct ir* ir, uint32_t index, enum irRegister reg, uint32_t primer);

struct node* ir_add_in_mem_(struct ir* ir, uint32_t index, uint8_t size, struct node* address, struct node* prev, ADDRESS concrete_address);
#define ir_add_in_mem(ir, index, size, address, prev) ir_add_in_mem_(ir, index, size, address, prev, MEMADDRESS_INVALID)

struct node* ir_add_out_mem_(struct ir* ir, uint32_t index, uint8_t size, struct node* address, struct node* prev, ADDRESS concrete_address);
#define ir_add_out_mem(ir, index, size, address, prev) ir_add_out_mem_(ir, index, size, address, prev, MEMADDRESS_INVALID)

struct node* ir_add_immediate(struct ir* ir, uint8_t size, uint64_t value);
struct node* ir_add_inst(struct ir* ir, uint32_t index, uint8_t size, enum irOpcode opcode, uint32_t dst);
struct node* ir_add_symbol(struct ir* ir, void* code_signature, void* result, uint32_t index);

struct node* ir_insert_immediate(struct ir* ir, struct node* root, uint8_t size, uint64_t value);
struct node* ir_insert_inst(struct ir* ir, struct node* root, uint32_t index, uint8_t size, enum irOpcode opcode, uint32_t dst);

static inline void ir_convert_node_to_inst(struct node* node, uint32_t index, uint8_t size, enum irOpcode opcode){
	struct irOperation* operation = ir_node_get_operation(node);

	/* Warning: it migth not be a good idea to discard the status flag without anymore check */

	if (operation->type == IR_OPERATION_TYPE_IN_MEM || operation->type == IR_OPERATION_TYPE_OUT_MEM){
		ir_mem_remove(operation);
	}

	operation->type 						= IR_OPERATION_TYPE_INST;
	operation->operation_type.inst.opcode 	= opcode;
	operation->operation_type.inst.dst 		= IR_OPERATION_DST_UNKOWN;
	operation->operation_type.inst.seed 	= IR_INVALID_RANGE_SEED;
	operation->size 						= size;
	operation->index 						= index;
	operation->status_flag 					= IR_OPERATION_STATUS_FLAG_NONE;
}

void ir_convert_node_to_imm(struct ir* ir, struct node* node, uint8_t size, uint64_t value);

struct edge* ir_add_dependence(struct ir* ir, struct node* operation_src, struct node* operation_dst, enum irDependenceType type);
struct edge* ir_add_macro_dependence(struct ir* ir, struct node* operation_src, struct node* operation_dst, uint32_t desc);

void ir_merge_equivalent_node(struct ir* ir, struct node* node_dst, struct node* node_src);

void ir_remove_node(struct ir* ir, struct node* node);
void ir_remove_dependence(struct ir* ir, struct edge* edge);

void ir_remove_footprint(struct ir* ir, struct node** node_buffer, uint32_t nb_node);

#define ir_printDot(ir) graphPrintDot_print(&((ir)->graph), NULL, NULL)

void ir_print_location_node(struct node* node, struct assembly* assembly);

void ir_print_node(struct irOperation* operation, FILE* file);
void ir_dotPrint_node(void* data, FILE* file, void* arg);
void ir_dotPrint_edge(void* data, FILE* file, void* arg);

/* Node Iterator - Required condition if one wants to delete node(s) while using the iterator
	- previously sorted form dst to src (respectively src to dst)
	- do not delete any node that is strictly lower (respectively strictly higher) than the current node
	- while adding new nodes minds the order. Once the order is broken, there is no guarantee anymore.
*/

struct irNodeIterator{
	struct node* curr_node;
	struct node* prev_node;
};

static inline struct node* irNodeIterator_get_first(struct ir* ir, struct irNodeIterator* it){
	it->curr_node = graph_get_head_node(&(ir->graph));
	it->prev_node = NULL;

	return it->curr_node;
}

static inline struct node* irNodeIterator_get_next(struct ir* ir, struct irNodeIterator* it){
	if (it->prev_node != NULL){
		if (node_get_next(it->prev_node) != it->curr_node){
			it->curr_node = node_get_next(it->prev_node);
		}
		else{
			it->prev_node = it->curr_node;
			it->curr_node = node_get_next(it->curr_node);
		}
	}
	else{
		if (graph_get_head_node(&(ir->graph)) != it->curr_node){
			it->curr_node = graph_get_head_node(&(ir->graph));
		}
		else{
			it->prev_node = it->curr_node;
			it->curr_node = node_get_next(it->curr_node);
		}
	}

	return it->curr_node;
}

#define irNodeIterator_get_node(it) ((it).curr_node)

#define ir_clean(ir) graph_clean(&((ir)->graph));

#define ir_delete(ir) 											\
	ir_clean(ir); 												\
	free(ir);

#include "irNormalize.h"
#include "irMemory.h"
#include "irCheck.h"
#include "irVariableSize.h"

#endif